### ISSUE TITLE
Experimenting with multiple hidden layers

### ISSUE THREAD

**Issue by BekLG** [NACLab/ngc-learn#71]
What’s the best way to experiment with multiple hidden layers? Can it be done without explicitly hardcoding each layer?

**Comment by ago109** [comment]
Great question! 
Currently, the best way to create multiple layers is for the user to decide on the repeating pattern between layers (e.g., a synaptic cable feeding into a node) and to create a loop that will auto-generate these for you. Note that the tricky part can be ensuring that you automate carefully the wiring pattern alongside creating the nodes (otherwise, you'll want to create a 2nd loop that goes through the layers and wires them correctly. 

Let's use a simple deep feedforward network/circuit (with static synapses) with several layers (here, we do four layers, one input, two hidden, and one output) with differently-sized hidden layers. Doing so amounts to the following:

```
from ngclearn import Context, numpy as jnp
from ngclearn.components import (RateCell, StaticSynapse)
from jax import jit, random
import ngclearn.utils.weight_distribution as dist

dims = [5, 4, 3, 2]

dkey = random.PRNGKey(1234)
dkey, *subkeys = random.split(dkey, len(dims)+1)
with Context("model") as model:
    ## build the chain of components (or "layers")
    execution_chain = [] ## here, we store all the nodes we create along the way
    z0 = RateCell(
        "z0", n_units=dims[0], tau_m=0., act_fx="identity"
    )
    execution_chain.append(z0)
    z_lm1 = z0 ## create a tmp variable (for layer below node)
    for l in range(1, len(dims)):
        z_lm1_dim = dims[l-1]
        z_l_dim = dims[l]
        W_l = StaticSynapse(
            f"W{l}", shape=(z_lm1_dim, z_l_dim),
            weight_init=dist.uniform(amin=-1., amax=1.), key=subkeys[l-1]
        )
        z_l = RateCell(f"z{l}", n_units=z_l_dim, tau_m=0., act_fx="relu")
        execution_chain += [W_l, z_l]
        ## wire input from layer l-1 to layer l
        W_l.inputs << z_lm1.zF
        z_l.j << W_l.outputs
        ## re-point tmp variable (layer l will layer l-1 in next loop iteration)
        z_lm1 = z_l

    ## set up simulation execution order
    advance, adv_args = model.compile_by_key(
        *execution_chain, compile_key="advance_state"
    )
    model.wrap_and_add_command(jit(model.advance_state), name="advance")

    @model.dynamicCommand
    def clamp_input(x):
        z0.j.set(x)

## now test model -- run a single feedforward pass
x = jnp.ones((1, dims[0]))
model.clamp_input(x)
model.advance(t=1., dt=1.)
print("Layer 0 (Input): ", model.get_components(f"z0").zF.value)
print("Layer 1 (Hidden): ", model.get_components(f"z1").zF.value)
print("Layer 2 (Hidden): ", model.get_components(f"z2").zF.value)
print("Layer 3 (Output): ", model.get_components(f"z3").zF.value)

```

which gives us an output similar to the following (you'll get a different set of numbers based on your computer's way of seeding your Jax rng, but the shapes should be the same as below):

```
Layer 0 (Input):  [[1. 1. 1. 1. 1.]]
Layer 1 (Hidden):  [[1.0266478 0.        3.518538  0.       ]]
Layer 2 (Hidden):  [[1.3525367 3.9293702 1.6835628]]
Layer 3 (Output):  [[3.58069 0.     ]]
```

Different modeling structures might require you to create different kinds of looping patterns but is often important  to identify what you want the very basic design pattern to be between layer l-1 and layer l. Note that you could likely further simplify/more cleanly write the building process by writing a function that builds the basic "block" containing the main nodes, synaptic cables, operators, etc. and their desired compartment-wiring configuration and then just call that each step of your model context building loop.

**Comment by BekLG** [comment]
@ago109, thank you for your reply and the detailed explanation.
